post http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "I had something interesting for breakfast"
}

###

post http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "I had something interesting for breakfast, kerfuffle",
  "extra": "Ignore me!"
}

put http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJDaGlycHktQWNjZXNzIiwic3ViIjoiMSIsImV4cCI6MTcwNTA2MTQzNywiaWF0IjoxNzA1MDU3ODM3fQ.8SWaEVCUIkj97LefGBwUtstYwdcZiCSeYTio6ERT9Z0

{
  "email": "sefu22@example.co",
  "password": "wompwomp2"
}

### 
post http://localhost:8080/api/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJDaGlycHktUmVmcmVzaCIsInN1YiI6IjEiLCJleHAiOjE3MDk4OTIyNjUsImlhdCI6MTcwNDcwODI2NX0.xn-Y5G1YSnbYnAstvTSMJqJqih83TXEauoucMxfYeJM

###
post http://localhost:8080/api/users

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

###
post http://localhost:8080/api/login

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

###
post http://localhost:8080/api/chirps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJDaGlycHktQWNjZXNzIiwic3ViIjoiMiIsImV4cCI6MTcwNTMyODI5NSwiaWF0IjoxNzA1MzI0Njk1fQ.tQhVZTcrCZ0fx_OzljHUoIQuoICk799mGV9YpJbafm0

{
  "body": "I really need a kerfuffle to go to bed sooner, Fornax now !"
}

###
delete http://localhost:8080/api/chirps/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJDaGlycHktQWNjZXNzIiwic3ViIjoiMiIsImV4cCI6MTcwNTMyODI5NSwiaWF0IjoxNzA1MzI0Njk1fQ.tQhVZTcrCZ0fx_OzljHUoIQuoICk799mGV9YpJbafm0

###
post http://localhost:8080/api/users

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

###
post http://localhost:8080/api/polka/webhooks

{
  "data": {
    "user_id": 1
  },
  "event": "user.payment_failed"
}

###
post http://localhost:8080/api/login

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

###
post http://localhost:8080/api/polka/webhooks

{
  "data": {
    "user_id": 1
  },
  "event": "user.upgraded"
}

###
post http://localhost:8080/api/login

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}
